server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: born2win
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: USER-SERVICE
  config:
    import: optional:configserver:http://localhost:8084

